name: Log Referral

on:
  repository_dispatch:
    types: [log-referral]

jobs:
  append_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Decode and append to CSV
        run: |
          echo "${{ github.event.client_payload.content }}" | base64 -d >> referral-log-trojan.csv

      - name: Commit and push
        run: |
          git config user.name "Referral Bot"
          git config user.email "bot@litocracy.org"
          git add referral-log-trojan.csv
          git commit -m "Append referral log"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
